/* Generated by scripts/generate_ts_client.py. */
export type ModelStatus = "draft" | "published" | "archived";

export interface ModelCreate {
  article: string;
  manufacturer?: string;
  series?: string | null;
  name?: string | null;
}

export interface ModelSummary {
  id: string;
  article: string;
  manufacturer: string;
  series?: string | null;
  name?: string | null;
  status: ModelStatus;
  activeRevisionId?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ModelList {
  items: ModelSummary[];
  nextCursor?: string | null;
}

export interface HealthResponse {
  status: "ok";
  service: string;
  version: string;
  database: "ok";
}

export interface UserInfo {
  subject: string;
  displayName: string;
  roles: string[];
  authMode: string;
}

export interface DraftSummary {
  id: string;
  modelId: string;
  baseRevisionId?: string | null;
  headRevisionToken: string;
  status: "open" | "committed" | "abandoned";
  createdAt: string;
  updatedAt: string;
}

export interface PatchCreate {
  baseRevisionToken: string;
  operations: Record<string, unknown>[];
}

export interface PatchSummary {
  id: string;
  draftId: string;
  actor: string;
  operations: Record<string, unknown>[];
  status: "accepted";
  createdAt: string;
}

export interface RevisionSummary {
  id: string;
  modelId: string;
  parentId?: string | null;
  schemaVersion: string;
  contentHash: string;
  createdAt: string;
}

export interface JobCreate {
  type: string;
  inputHash: string;
  payload?: Record<string, unknown>;
}

export interface JobSummary {
  id: string;
  type: string;
  state: "queued" | "running" | "succeeded" | "failed" | "cancelled";
  inputHash: string;
  idempotencyKey?: string | null;
  attempt: number;
  progress: number;
  workerId?: string | null;
  heartbeatAt?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface JobAccepted {
  jobId: string;
  status: "queued" | "running";
  affectedComponentIds: string[];
  eventsUrl: string;
}

export interface ReleaseSummary {
  id: string;
  revisionId: string;
  profile: string;
  status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
  jobId?: string | null;
  manifestArtifactId?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface UploadIntent {
  artifactId: string;
  uploadUrl: string;
  objectKey: string;
  expiresAt: string;
}

export interface ArtifactSummary {
  id: string;
  objectKey: string;
  sha256: string;
  mediaType: string;
  size: number;
  scope: string;
  status: "pending" | "ready";
  createdAt: string;
}

export interface DownloadUrl {
  artifactId: string;
  downloadUrl: string;
  expiresAt: string;
}

export class StudioApiClient {
  constructor(
    private readonly baseUrl = "",
    private readonly defaultHeaders: Record<string, string> = {},
  ) {}

  async health(): Promise<HealthResponse> {
    return this.request<HealthResponse>("/health");
  }

  async me(): Promise<UserInfo> {
    return this.request<UserInfo>("/api/v1/auth/me");
  }

  async listModels(params: { query?: string; limit?: number } = {}): Promise<ModelList> {
    const query = new URLSearchParams();
    if (params.query) query.set("query", params.query);
    if (params.limit) query.set("limit", String(params.limit));
    const suffix = query.toString() ? `?${query.toString()}` : "";
    return this.request<ModelList>(`/api/v1/models${suffix}`);
  }

  async createModel(payload: ModelCreate): Promise<ModelSummary> {
    return this.request<ModelSummary>("/api/v1/models", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
  }

  async getModel(modelId: string): Promise<ModelSummary> {
    return this.request<ModelSummary>(`/api/v1/models/${encodeURIComponent(modelId)}`);
  }

  async createDraft(modelId: string, payload: { baseRevisionId?: string | null } = {}): Promise<DraftSummary> {
    return this.request<DraftSummary>(`/api/v1/models/${encodeURIComponent(modelId)}/drafts`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
  }

  async getDraft(draftId: string): Promise<DraftSummary> {
    return this.request<DraftSummary>(`/api/v1/drafts/${encodeURIComponent(draftId)}`);
  }

  async applyPatch(draftId: string, payload: PatchCreate): Promise<PatchSummary> {
    return this.request<PatchSummary>(`/api/v1/drafts/${encodeURIComponent(draftId)}/patches`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
  }

  async commitDraft(
    draftId: string,
    payload: { baseRevisionToken: string; schemaVersion?: string; pmd: Record<string, unknown> },
  ): Promise<RevisionSummary> {
    return this.request<RevisionSummary>(`/api/v1/drafts/${encodeURIComponent(draftId)}/commit`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
  }

  async abandonDraft(draftId: string): Promise<void> {
    await this.request<void>(`/api/v1/drafts/${encodeURIComponent(draftId)}`, {
      method: "DELETE",
    });
  }

  async enqueueJob(payload: JobCreate, idempotencyKey?: string): Promise<JobSummary> {
    const headers: Record<string, string> = { "content-type": "application/json" };
    if (idempotencyKey) headers["Idempotency-Key"] = idempotencyKey;
    return this.request<JobSummary>("/api/v1/jobs", {
      method: "POST",
      headers,
      body: JSON.stringify(payload),
    });
  }

  async getJob(jobId: string): Promise<JobSummary> {
    return this.request<JobSummary>(`/api/v1/jobs/${encodeURIComponent(jobId)}`);
  }

  async cancelJob(jobId: string): Promise<JobSummary> {
    return this.request<JobSummary>(`/api/v1/jobs/${encodeURIComponent(jobId)}/cancel`, { method: "POST" });
  }

  async retryJob(jobId: string): Promise<JobSummary> {
    return this.request<JobSummary>(`/api/v1/jobs/${encodeURIComponent(jobId)}/retry`, { method: "POST" });
  }

  async claimJob(payload: { workerId: string; types?: string[] }): Promise<JobSummary | null> {
    return this.request<JobSummary | null>("/api/v1/workers/claim", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
  }

  async heartbeatJob(jobId: string, payload: { workerId: string; progress: number }): Promise<JobSummary> {
    return this.request<JobSummary>(`/api/v1/jobs/${encodeURIComponent(jobId)}/heartbeat`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
  }

  async previewDraft(
    draftId: string,
    payload: { baseRevisionToken: string; profile?: string; clientRequestId?: string | null },
    idempotencyKey?: string,
  ): Promise<JobAccepted> {
    const headers: Record<string, string> = { "content-type": "application/json" };
    if (idempotencyKey) headers["Idempotency-Key"] = idempotencyKey;
    return this.request<JobAccepted>(`/api/v1/drafts/${encodeURIComponent(draftId)}/preview`, {
      method: "POST",
      headers,
      body: JSON.stringify(payload),
    });
  }

  async createRelease(
    revisionId: string,
    payload: { profile?: string; clientRequestId?: string | null } = {},
    idempotencyKey?: string,
  ): Promise<ReleaseSummary> {
    const headers: Record<string, string> = { "content-type": "application/json" };
    if (idempotencyKey) headers["Idempotency-Key"] = idempotencyKey;
    return this.request<ReleaseSummary>(`/api/v1/revisions/${encodeURIComponent(revisionId)}/releases`, {
      method: "POST",
      headers,
      body: JSON.stringify(payload),
    });
  }

  async getRelease(releaseId: string): Promise<ReleaseSummary> {
    return this.request<ReleaseSummary>(`/api/v1/releases/${encodeURIComponent(releaseId)}`);
  }

  async createUploadIntent(payload: {
    filename: string;
    mediaType: string;
    size: number;
    sha256: string;
    scope?: string;
  }): Promise<UploadIntent> {
    return this.request<UploadIntent>("/api/v1/documents/upload-intents", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
  }

  async completeUpload(artifactId: string): Promise<ArtifactSummary> {
    return this.request<ArtifactSummary>("/api/v1/documents/complete-upload", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ artifactId }),
    });
  }

  async getArtifact(artifactId: string): Promise<ArtifactSummary> {
    return this.request<ArtifactSummary>(`/api/v1/artifacts/${encodeURIComponent(artifactId)}`);
  }

  async getDownloadUrl(artifactId: string): Promise<DownloadUrl> {
    return this.request<DownloadUrl>(`/api/v1/artifacts/${encodeURIComponent(artifactId)}/download-url`);
  }

  private async request<T>(path: string, init: RequestInit = {}): Promise<T> {
    const headers = { ...this.defaultHeaders, ...(init.headers || {}) };
    const response = await fetch(`${this.baseUrl}${path}`, { ...init, headers });
    if (!response.ok) {
      throw new Error(`LANMASTER Studio API ${response.status}: ${await response.text()}`);
    }
    if (response.status === 204) {
      return undefined as T;
    }
    return response.json() as Promise<T>;
  }
}
