import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import assert from "node:assert/strict";

const root = resolve(import.meta.dirname, "..");
const apiSource = await readFile(resolve(root, "src/api.ts"), "utf8");
const appSource = await readFile(resolve(root, "src/main.tsx"), "utf8");

assert.match(apiSource, /X-Dev-User/);
assert.match(apiSource, /X-Dev-Roles/);
assert.match(apiSource, /StudioApiClient/);
assert.match(appSource, /\/models\/new/);
assert.match(appSource, /\/models\/\$\{model\.id\}/);
assert.match(appSource, /client\.me\(\)/);
assert.match(appSource, /client\.listModels/);
assert.match(appSource, /client\.getModel/);
assert.match(appSource, /client\.listRevisions/);
assert.match(appSource, /client\.getRevision/);
assert.match(appSource, /Revision selector/);
assert.match(appSource, /buildDemoTree\(1000\)/);
assert.match(appSource, /buildTreeFromPmd/);
assert.match(appSource, /buildPropertiesFromPmd/);
assert.match(appSource, /TREE_ROW_HEIGHT = 32/);
assert.match(appSource, /TREE_VIEWPORT_HEIGHT = 384/);
assert.match(appSource, /translateY/);
assert.match(appSource, /new THREE\.WebGLRenderer/);
assert.match(appSource, /renderer\.dispose\(\)/);
assert.match(appSource, /requestAnimationFrame/);
assert.match(appSource, /selectedComponentId/);
assert.match(appSource, /onSelectComponent/);
assert.match(appSource, /componentId/);
assert.match(appSource, /Raycaster/);
assert.match(appSource, /viewerMode/);
assert.match(appSource, /Visibility/);
assert.match(appSource, /Exploded view/);
assert.match(appSource, /Measure/);
assert.match(appSource, /Section/);
assert.match(appSource, /PropertyEditor/);
assert.match(appSource, /sourceStatus/);
assert.match(appSource, /schema-driven/);
assert.match(appSource, /min=/);
assert.match(appSource, /unit/);
assert.match(appSource, /PreviewWorkflow/);
assert.match(appSource, /previewDraft/);
assert.match(appSource, /applyPatch/);
assert.match(appSource, /cancelJob/);
assert.match(appSource, /retryJob/);
assert.match(appSource, /Progress/);
assert.match(appSource, /DiffQaPanel/);
assert.match(appSource, /Undo/);
assert.match(appSource, /Redo/);
assert.match(appSource, /Accept baseline/);
assert.match(appSource, /patch visible before commit/);
assert.match(appSource, /CommitReleasePanel/);
assert.match(appSource, /commitDraft/);
assert.match(appSource, /basePmd/);
assert.match(appSource, /createRelease/);
assert.match(appSource, /Release draft/);
assert.match(appSource, /History/);
assert.match(appSource, /aria-label="LANMASTER Studio workspace"/);

console.log("Frontend scaffold verification passed");
