#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "clients" / "typescript" / "src" / "index.ts"


CLIENT = """/* Generated by scripts/generate_ts_client.py. */
export type ModelStatus = "draft" | "published" | "archived";

export interface ModelCreate {
  article: string;
  manufacturer?: string;
  series?: string | null;
  name?: string | null;
}

export interface ModelSummary {
  id: string;
  article: string;
  manufacturer: string;
  series?: string | null;
  name?: string | null;
  status: ModelStatus;
  activeRevisionId?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ModelList {
  items: ModelSummary[];
  nextCursor?: string | null;
}

export interface HealthResponse {
  status: "ok";
  service: string;
  version: string;
  database: "ok";
}

export interface UserInfo {
  subject: string;
  displayName: string;
  roles: string[];
  authMode: string;
}

export interface DraftSummary {
  id: string;
  modelId: string;
  baseRevisionId?: string | null;
  headRevisionToken: string;
  status: "open" | "committed" | "abandoned";
  createdAt: string;
  updatedAt: string;
}

export interface PatchCreate {
  baseRevisionToken: string;
  operations: Record<string, unknown>[];
}

export interface PatchSummary {
  id: string;
  draftId: string;
  actor: string;
  operations: Record<string, unknown>[];
  status: "accepted";
  createdAt: string;
}

export interface RevisionSummary {
  id: string;
  modelId: string;
  parentId?: string | null;
  schemaVersion: string;
  contentHash: string;
  createdAt: string;
}

export class StudioApiClient {
  constructor(
    private readonly baseUrl = "",
    private readonly defaultHeaders: Record<string, string> = {},
  ) {}

  async health(): Promise<HealthResponse> {
    return this.request<HealthResponse>("/health");
  }

  async me(): Promise<UserInfo> {
    return this.request<UserInfo>("/api/v1/auth/me");
  }

  async listModels(params: { query?: string; limit?: number } = {}): Promise<ModelList> {
    const query = new URLSearchParams();
    if (params.query) query.set("query", params.query);
    if (params.limit) query.set("limit", String(params.limit));
    const suffix = query.toString() ? `?${query.toString()}` : "";
    return this.request<ModelList>(`/api/v1/models${suffix}`);
  }

  async createModel(payload: ModelCreate): Promise<ModelSummary> {
    return this.request<ModelSummary>("/api/v1/models", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
  }

  async getModel(modelId: string): Promise<ModelSummary> {
    return this.request<ModelSummary>(`/api/v1/models/${encodeURIComponent(modelId)}`);
  }

  async createDraft(modelId: string, payload: { baseRevisionId?: string | null } = {}): Promise<DraftSummary> {
    return this.request<DraftSummary>(`/api/v1/models/${encodeURIComponent(modelId)}/drafts`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
  }

  async getDraft(draftId: string): Promise<DraftSummary> {
    return this.request<DraftSummary>(`/api/v1/drafts/${encodeURIComponent(draftId)}`);
  }

  async applyPatch(draftId: string, payload: PatchCreate): Promise<PatchSummary> {
    return this.request<PatchSummary>(`/api/v1/drafts/${encodeURIComponent(draftId)}/patches`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
  }

  async commitDraft(
    draftId: string,
    payload: { baseRevisionToken: string; schemaVersion?: string; pmd: Record<string, unknown> },
  ): Promise<RevisionSummary> {
    return this.request<RevisionSummary>(`/api/v1/drafts/${encodeURIComponent(draftId)}/commit`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
  }

  async abandonDraft(draftId: string): Promise<void> {
    await this.request<void>(`/api/v1/drafts/${encodeURIComponent(draftId)}`, {
      method: "DELETE",
    });
  }

  private async request<T>(path: string, init: RequestInit = {}): Promise<T> {
    const headers = { ...this.defaultHeaders, ...(init.headers || {}) };
    const response = await fetch(`${this.baseUrl}${path}`, { ...init, headers });
    if (!response.ok) {
      throw new Error(`LANMASTER Studio API ${response.status}: ${await response.text()}`);
    }
    if (response.status === 204) {
      return undefined as T;
    }
    return response.json() as Promise<T>;
  }
}
"""


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(CLIENT, encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
