#!/usr/bin/env python3
from __future__ import annotations

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "clients" / "typescript" / "src" / "index.ts"


CLIENT = """/* Generated by scripts/generate_ts_client.py. */
export type ModelStatus = "draft" | "published" | "archived";

export interface ModelCreate {
  article: string;
  manufacturer?: string;
  series?: string | null;
  name?: string | null;
}

export interface ModelSummary {
  id: string;
  article: string;
  manufacturer: string;
  series?: string | null;
  name?: string | null;
  status: ModelStatus;
  activeRevisionId?: string | null;
  createdAt: string;
  updatedAt: string;
}

export interface ModelList {
  items: ModelSummary[];
  nextCursor?: string | null;
}

export interface HealthResponse {
  status: "ok";
  service: string;
  version: string;
  database: "ok";
}

export class StudioApiClient {
  constructor(private readonly baseUrl = "") {}

  async health(): Promise<HealthResponse> {
    return this.request<HealthResponse>("/health");
  }

  async listModels(params: { query?: string; limit?: number } = {}): Promise<ModelList> {
    const query = new URLSearchParams();
    if (params.query) query.set("query", params.query);
    if (params.limit) query.set("limit", String(params.limit));
    const suffix = query.toString() ? `?${query.toString()}` : "";
    return this.request<ModelList>(`/api/v1/models${suffix}`);
  }

  async createModel(payload: ModelCreate): Promise<ModelSummary> {
    return this.request<ModelSummary>("/api/v1/models", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(payload),
    });
  }

  async getModel(modelId: string): Promise<ModelSummary> {
    return this.request<ModelSummary>(`/api/v1/models/${encodeURIComponent(modelId)}`);
  }

  private async request<T>(path: string, init: RequestInit = {}): Promise<T> {
    const response = await fetch(`${this.baseUrl}${path}`, init);
    if (!response.ok) {
      throw new Error(`LANMASTER Studio API ${response.status}: ${await response.text()}`);
    }
    return response.json() as Promise<T>;
  }
}
"""


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(CLIENT, encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
